GET http://localhost:3001/api/blogs/

###

GET http://localhost:3001/api/blogs/621e8822d24deb5e7087021f

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbmFuIiwiaWQiOiI2MjFmYzljNWNkYjI5OTBiMWE0MGUzNTEiLCJpYXQiOjE2NDYyNTEwMTh9.sRchbcqqQS6eRBsM6YfKEsMGCWDQJU_yx4x7lztW4Rw 

{"title": "hi",
 "url": "hello",
  "author": "auth",
  "likes": "555",
  "userId":"621f91d4d11192a23e120564" 
}
###
DELETE http://localhost:3001/api/blogs/621cfef78971f2c6da8a8ae6

###
PUT http://localhost:3001/api/blogs/621e88dfd24deb5e7087022e
Content-Type: application/json

{
  "author": "AUTHii",
  "likes": "55345"
}

