GET http://localhost:3001/api/users/

###

GET http://localhost:3001/api/users/621f91d4d11192a23e120564

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "username": "12345",
    "name": "12345",
    "password": "12345"
}
###
DELETE http://localhost:3001/api/users/621cfef78971f2c6da8a8ae6

###
PUT http://localhost:3001/api/users/621e88dfd24deb5e7087022e
Content-Type: application/json

{
  "username": "root1",
    "name": "Superuser1",
}

